import { IProduct } from "./iproduct";

export  let productList:IProduct[]=[
  { id:1,
    image:"https://images.pexels.com/photos/15928603/pexels-photo-15928603/free-photo-of-red-subaru-forester-on-dirt-road.jpeg?auto=compress&cs=tinysrgb&w=600",
    name:"Car",
    description:"Car red",
    price:20000,
    onSale:true,
    discount:5,
    quantity:1},
    { id:2,
      image:"https://images.pexels.com/photos/699122/pexels-photo-699122.jpeg?auto=compress&cs=tinysrgb&w=600",
      name:"Mobile",
      description:"Mobile red",
      price:9000,
      onSale:true,
      discount:10,
      quantity:1},
      { id:3,
        image:"https://images.pexels.com/photos/18105/pexels-photo.jpg?auto=compress&cs=tinysrgb&w=600",
        name:"Labtop",
        description:"Labtop red",
        price:17000,
        onSale:true,
        discount:15,
        quantity:1},
        { id:4,
          image:"https://images.pexels.com/photos/601316/pexels-photo-601316.jpeg?auto=compress&cs=tinysrgb&w=600",
          name:"Skirt",
          description:"Skirt red",
          price:300,
          onSale:true,
          discount:.06,
          quantity:2},
          { id:5,
            image:"https://images.pexels.com/photos/8532616/pexels-photo-8532616.jpeg?auto=compress&cs=tinysrgb&w=600",
            name:"T-Shirt",
            description:"T-Shirt red",
            price:200,
            onSale:true,
            discount:9,
            quantity:2}
]
